/* Auto-generated by scripts/prepare-real-images.mjs — do not edit by hand */

export const streamImages: Array<{ src: string; alt: string }> = [
  {
    "src": "/images/real/stream/01-fachada.jpg",
    "alt": "Fábio Ótica, fachada"
  },
  {
    "src": "/images/real/stream/02-entrada.jpg",
    "alt": "Fábio Ótica, entrada"
  },
  {
    "src": "/images/real/stream/03-recepcao.jpg",
    "alt": "Fábio Ótica, recepcao"
  },
  {
    "src": "/images/real/stream/04-armacoes.jpg",
    "alt": "Fábio Ótica, armacoes"
  },
  {
    "src": "/images/real/stream/05-visao-geral.jpg",
    "alt": "Fábio Ótica, visao geral"
  },
  {
    "src": "/images/real/stream/06-panorama.jpg",
    "alt": "Fábio Ótica, panorama"
  },
  {
    "src": "/images/real/stream/07-cliente.jpg",
    "alt": "Fábio Ótica, cliente"
  },
  {
    "src": "/images/real/stream/08-detalhe-armacoes.jpg",
    "alt": "Fábio Ótica, detalhe armacoes"
  },
  {
    "src": "/images/real/stream/09-oculos-esportivos.jpg",
    "alt": "Fábio Ótica, oculos esportivos"
  },
  {
    "src": "/images/real/stream/10-expositor.jpg",
    "alt": "Fábio Ótica, expositor"
  },
  {
    "src": "/images/real/stream/11-colecao.jpg",
    "alt": "Fábio Ótica, colecao"
  },
  {
    "src": "/images/real/stream/12-armacao-destaque.jpg",
    "alt": "Fábio Ótica, armacao destaque"
  },
  {
    "src": "/images/real/stream/13-mostruario.jpg",
    "alt": "Fábio Ótica, mostruario"
  },
  {
    "src": "/images/real/stream/14-ambiente.jpg",
    "alt": "Fábio Ótica, ambiente"
  },
  {
    "src": "/images/real/stream/15-vitrine.jpg",
    "alt": "Fábio Ótica, vitrine"
  },
  {
    "src": "/images/real/stream/16-prateleira.jpg",
    "alt": "Fábio Ótica, prateleira"
  },
  {
    "src": "/images/real/stream/17-detalhe-lentes.jpg",
    "alt": "Fábio Ótica, detalhe lentes"
  },
  {
    "src": "/images/real/stream/18-selecao.jpg",
    "alt": "Fábio Ótica, selecao"
  },
  {
    "src": "/images/real/stream/19-atendimento.jpg",
    "alt": "Fábio Ótica, atendimento"
  },
  {
    "src": "/images/real/stream/20-consulta.jpg",
    "alt": "Fábio Ótica, consulta"
  },
  {
    "src": "/images/real/stream/21-personalizados.jpg",
    "alt": "Fábio Ótica, personalizados"
  },
  {
    "src": "/images/real/stream/22-oculos-sol.jpg",
    "alt": "Fábio Ótica, oculos sol"
  },
  {
    "src": "/images/real/stream/23-estilo.jpg",
    "alt": "Fábio Ótica, estilo"
  },
  {
    "src": "/images/real/stream/24-interior.jpg",
    "alt": "Fábio Ótica, interior"
  },
  {
    "src": "/images/real/stream/25-marca.jpg",
    "alt": "Fábio Ótica, marca"
  }
];
